### PR TITLE
remove polyfills

### PR DESCRIPTION
**Pull request by billybonks**
the only reason i could see for keeping these is so that apps that use this add on and that are pre v2.5 can have these polyfills. but that should be up to those app owners. Also i am not sure if devDependencies propergate when you publish an ember addon.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@billybonks I mean to support previous versions with these, but you are right, they will not get shipped since they are devDeps. Since no one has complained about this, I think removing them is fine. Can you please update yarn.lock as well?

**Comment by billybonks** [comment]
i guess we should keep them in because otherwise your tests won't run :).

**Comment by billybonks** [comment]
https://travis-ci.org/shipshapecode/ember-shepherd/jobs/347335793

**Comment by rwwagner90** [comment]
@billybonks do you want to move them to deps instead of devDeps?

**Comment by billybonks** [comment]
i would be just concerned that if they are in deps a 3.0 app wouldn't pull them in haven't looked through the broccoli funnels of ember-cli but i think they are quite eager

**Comment by rwwagner90** [comment]
@billybonks a 3.0 app doesn't need the polyfills

**Comment by billybonks** [comment]
And embercamp knows this so it will probably just if ignore the dependency.
Sure I'll open a pr that moves it to dependencies

**Comment by rwwagner90** [comment]
I'm not sure what you mean. It won't ignore the dep. It will pull in the dep and polyfill as needed.

**Comment by billybonks** [comment]
ye that's what i meant :)

**Comment by rwwagner90** [comment]
@billybonks so we still need to move them to deps then, if you'd like to open a PR. If not, I can just move them over real quick.

**Pull request closed without merging**
