### PR TITLE
Document required elements order; add requiredElements tests

### PR DESCRIPTION
**Pull request by BrianSipple**
I noticed that `requiredElements` needs to be set before `steps` -- because that's when we actually perform the check for their presence.

I updated the dummy app to reflect this, too.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@BrianSipple any ideas why these tests keep failing? Does moving the setting of the steps cause this somehow?

**Comment by BrianSipple** [comment]
Interesting, yeah the acceptance test appears to be crashing on boot. Looking in to it now.

**Comment by BrianSipple** [comment]
Okay, so this is failing because the DOM hasn't rendered yet when the `stepsChange` observer fires and runs `this.requiredElementsPresent()`. 

Could this issue be highlighting how `requiredElements` doesn't really work in its present form? We can't properly check it unless we require users to set steps after rendering -- which seems less than ideal. 

Perhaps breaking things out of the observer as part of https://github.com/shipshapecode/ember-shepherd/issues/242 can help solve this.

**Comment by rwwagner90** [comment]
@BrianSipple I just merged https://github.com/shipshapecode/ember-shepherd/pull/260 which replaces the observer with an explicit `addSteps` method. Can we see if we can get this fixed up now?

**Comment by BrianSipple** [comment]
@rwwagner90 This seems to work as expected now. I rebased and also added a few acceptance tests around `requiredElements`

**Pull request merged**
