### PR TITLE
Run debounced modal opening positioning immediately

### PR DESCRIPTION
**Pull request by scottkidder**

### CODE REVIEW

**Comment by scottkidder** [comment]
This is required to get the modal overlays correctly positioned in our visual testing setup using [ember-visual-test](https://github.com/Cropster/ember-visual-test)

**Comment by rwwagner90** [comment]
@BrianSipple any reason we wouldn't want this? I don't know if it effects animations

**Comment by BrianSipple** [comment]
I'm not seeing any adverse effects after running locally. LGTM 👍

**Comment by scottkidder** [comment]
Thanks gents!

**Pull request merged**
