### PR TITLE
Change builtInButtons to buttons

### LINKED ISSUE #224: Clarify/change builtInButtons
We still call this `builtInButtons`, but it actually supports custom buttons too now, so we should update docs and possibly change the name.

### PR DESCRIPTION
**Pull request by chuckcarpenter**
This branch obfuscates the binding for buttons in steps to the user and makes setup mirror the docs from Shepherd.js. 

Resolves #224

### CODE REVIEW

**Comment by rwwagner90** [comment]
@chuckcarpenter I don't think we should call something that's not the same as Shepherd, the same as Shepherd here. `builtInButtons` have a type and generate a button that is built into ember-shepherd. These include cancel, back, next, etc. If we're trying to align with Shepherd and just be a pass through, this will be confusing to people, I think, right?

**Comment by rwwagner90** [comment]
I'm still in favor of merging `builtInButtons` output and `buttons` if you want vanilla Shepherd buttons.

**Comment by BrianSipple** [comment]
It seems like the primary issue here is that the interface lacks constraint. What if we had two separate options: `shepherdButtons` and `customButtons`. Each is focused, explicit, and unambiguous -- unlike `builtInButtons` and `buttons`, apparently 😛.

**Comment by rwwagner90** [comment]
@BrianSipple I would keep `builtInButtons` I think. The buttons are built in and provided. `customButtons` makes it sound like you want to do something custom.

We could potentially use just `buttons` I suppose, and add a check for `type`. If you pass `type` we use a built in one we provide, if you do not, it's just treated like a vanilla Shepherd button. What do you think @chuckcarpenter?

**Comment by BrianSipple** [comment]
> customButtons makes it sound like you want to do something custom.

Right, isn't that what we're trying to enable? The current confusion is from the fact that `builtInButtons` allows you to select from one of `shepherd`'s buttons _and_ pass in something different. Or am I confused about what we're confused about?

**Comment by rwwagner90** [comment]
@BrianSipple Shepherd does not provide any buttons.

**Comment by rwwagner90** [comment]
Totally agree @BrianSipple! We just need to fix conflicts here and add the `type` check stuff.

**Pull request merged**
