### PR TITLE
Add option to force users to confirm tour cancels (using native browser prompt)

### PR DESCRIPTION
**Pull request by djsegal**
Attempt to resolve: Issue https://github.com/shipshapecode/ember-shepherd/issues/56

### CODE REVIEW

**Comment by rwwagner90** [comment]
@djsegal have you tried this out on your end and it works?

**Comment by rwwagner90** [comment]
@djsegal I implemented this functionality myself, just now. Please try 2.1.5 and see if it works for you!

**Comment by djsegal** [comment]
@rwwagner90 sadly, the way you implemented it doesn't work 😞

+ the cancel button is directly bound to an anonymous function that calls cancel (inside shepherd).
+ that's why I had to nest the entire cancel function inside itself

**Comment by rwwagner90** [comment]
@djsegal it 100% works. I tested it myself. How does it not work for you?

**Comment by djsegal** [comment]
@rwwagner90 you're using the exit button. im talking about the 'X' in the top right of the div

screen shot 2016-08-17 at 11 49 21 am

-----

this is what is bound to cancel in an anonymous function inside the shepherd repo

**Comment by rwwagner90** [comment]
Ah okay. Good catch. We probably need to wrap that x with this lib too

**Comment by rwwagner90** [comment]
@djsegal really sorry about misunderstanding what you needed here. I should have merged this. I updated to use your solution and gave you credit in the CHANGELOG. I published version 2.2.0 with the fix. Please give it a try!

**Pull request closed without merging**
