### PR TITLE
trying to support fastboot

### PR DESCRIPTION
**Pull request by joshfester**
jQuery causes problems when trying to run with fastboot

### CODE REVIEW

**Comment by rwwagner90** [comment]
@joshfester we are probably going to need to wrap all those imports in that if, as Shepherd itself also uses `window` and things fastboot cannot use. Could you adjust your PR please?

**Comment by joshfester** [comment]
@rwwagner90 I was testing a pretty small app, but I was able to get Fastboot working by only worrying about jquery.disablescroll. It seems the other libraries encapsulate their jQuery usage enough for Fastboot

**Comment by rwwagner90** [comment]
@joshfester I suppose Shepherd must not try to add itself to window, if there is no window? I thought that would be an issue, perhaps.

**Comment by joshfester** [comment]
I believe the problem was with jquery.disablescroll being an anonymous function that runs calls jQuery as soon as it's imported. Shepherd itself seemed to be fine

**Comment by rwwagner90** [comment]
Merged and released an update. Please give it a try @joshfester!

**Comment by joshfester** [comment]
@rwwagner90 will do, thanks!

**Comment by rwwagner90** [comment]
@joshfester no problem! If you find the library useful, please feel free to star it 😄 . Also, if you have suggestions for features I'd be glad to help implement them.

**Pull request merged**
