### PR TITLE
Adds show() functionality.

### PR DESCRIPTION
**Pull request by sicdigital**
Allows the ability to skip to another step in the tour.

### CODE REVIEW

**Comment by rwwagner90** [comment]
Hi @sicdigital, what does this accomplish? Can you also add tests please?

**Comment by sicdigital** [comment]
This lets you use the native show() functionality in the form `this.get('tour').show('foo_step');`

Full shepherd code here

> https://github.com/HubSpot/shepherd/blob/master/src/js/shepherd.js#L277

I'll update the PR with tests

**Comment by rwwagner90** [comment]
@sicdigital I assume this is helpful for manually manipulating the step you are showing, rather than using the built in next, previous, etc? If you can add a quick test and get travis passing, I will be glad to merge and release a new version.

**Comment by rwwagner90** [comment]
@sicdigital do you think you will have time to write a test and get Travis passing?

**Comment by rwwagner90** [comment]
@sicdigital bump

**Comment by rwwagner90** [comment]
@sicdigital I am going to have to either close this or test it myself, if you do not respond.

**Comment by sicdigital** [comment]
Sorry, I'll have a look at this later in the evening. I'm currently using
my fork in my project, would much prefer to rely on the original repo.

Michael Chacon
*SIC Digital Creative Agency *

:: phone:: 305-741-4742
:: web:: http:// sicdigital.com

:: facebook:: sicwp
:: instagram:: sicdigital

:: office :: 133 NE 2nd Ave #1002
:: Miami, FL

**Comment by rwwagner90** [comment]
@sicdigital maybe I can help write some tests. This PR is over a month old now

**Comment by rwwagner90** [comment]
@sicdigital any chance you'd like to write some tests soon? 😄

**Comment by rwwagner90** [comment]
@sicdigital this has been sitting far too long. I'm going to merge without tests, and we'll have to test it ourselves in the future. I will not accept any more PRs without tests though.

**Comment by rwwagner90** [comment]
@sicdigital I published 2.3.2 with these changes, so you can point to an official version now 🎉

**Pull request merged**
