### PR TITLE
[#206] Make parent element for modal overlay customizable

### LINKED ISSUE #206: Allow user to decide where to place the `shepherdOverlay` element
## Current behavior
The element gets appended to `body`. In my case, it's a bit complicated since I have to place it in a different element to make the highlighting work properly.

## Proposed behavior
The user can pass in an optional config option `modalContainer` (defaults to `body`) which influences where the modal element will be placed. Usage:

```js
// tour setup goes here
tour.setProperties({
  modal: true, 
  modalContainer: '.some-modal-container'
});
```

Let me know what you think :) Happy to create a PR in case the proposal is accepted.

### PR DESCRIPTION
**Pull request by jbandura**
Resolves #206.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@jbandura were the tests working for you locally? Travis is failing because `find` only takes one argument.

**Comment by rwwagner90** [comment]
I'm going to merge this and fix the tests. Thanks for the PR!

**Comment by jbandura** [comment]
Thank you 🎉 sorry for not answering but had a pretty crazy time recently - I'm pretty sure the tests were passing on my machine 🤔 (I know it's the most lame dev excuse ever 😅)

**Comment by rwwagner90** [comment]
No worries! I think it was just an issue with the global `find` versus the imported one perhaps. Got them passing after the fact.

**Pull request merged**
